# For information on how to configure ColeBans, go to http://c2wr.com/cbconf
# banHandler can be MySQL or YAML. MCBans is being worked on (as of 6/28/2012)
# Please note that if fancyEffects is disabled, the banhammer will not work.
###### APIKEY IS VERY VERY IMPORTANT IF YOU CHOSE MCBANS FOR THE BAN HANDLER ######
settings:
    allowTempBans: yes
    banMessage: You are banned for %reason!
    tempBanMessage: You are tempbanned! %time minute%plural remaining!
    fancyEffects: yes
    banColor: DARK_RED
    kickColor: YELLOW
    tempBanColor: RED
    announceBansAndKicks: yes
    allowIPLog: yes
    banHandler: YAML
    banhammer:
        enable: yes
        type: GOLD_HOE
        leftClickAction: BAN
        rightClickAction: KICK
        allowSmite: yes
        reason: Banhammered
    mysql:
        user: root
        pass: pass
        host: localhost
        db: minecraft
        prefix: cb_
    mcbans:
        apiKey: yourAPIKeyHere
        backup: None
        fullBackups: no
        minRep: 10
    yaml:
        fileName: banlist.yml
    advanced:
        package: com.cole2sworld.ColeBans.handlers
        suffix: BanHandler